repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: mixed-line-ending

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    files: |
      (?x)(
        ^src/|
        ^tests/|
        ^apps/
      )

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0  # pick a git hash / tag to point to
  hooks:
    - id: pydocstyle

